micronaut:
  application:
    name: pix-worker
  server:
    port: 8081

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/pixdb
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9092
