micronaut:
  application:
    name: pix-api
  server:
    cors:
      enabled: true
      configurations:
        frontend:
          allowed-origins:
              - "http://localhost:5173"
          allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - X-Requested-With
          exposed-headers:
              - "Location"
          max-age: 3600

kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    default: # Configurações padrão para quem envia mensagens
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.micronaut.configuration.kafka.serde.JsonSerde # Serializa objetos em JSON automático

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/pixdb # Mesma URL do Worker
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES